name: CI/CD Backend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tiaperez/backend-innovatech:latest

      - name: Deploy en EC2 Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull tiaperez/backend-innovatech:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend \
              -p 3000:3000 \
              tiaperez/backend-innovatech:latest
